# Notebook 1: Tensors
In this notebook we will see some generalities on pytorch tensors

In [2]:
import torch
import numpy as np

### Initializing a tensors
We can initialize a tensor from
* data
* a numpy array
* another tensor

Some functions are available to initialize tensors with zeros, random values, ones

In [4]:
# Initialize a tensor from data
data = [[1,2],[3,4]]
x_data = torch.tensor(data)
# Initialize a tensor from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
# Initialize a tensor with random or constant values
shape = (2,3,)
rand_tensor = torch.rand(shape) # random numbers in [0,1]
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
# Initialize a tensor from another tensor
x_ones = torch.ones_like(x_data) # retains the properties of x_data
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data


In [5]:
# Print the tensors
print(f"Data Tensor: \n{x_data} \n")
print(f"From numpy array: \n{x_np} \n")
print(f"Random Tensor: \n{rand_tensor} \n")
print(f"Ones Tensor: \n{ones_tensor} \n")
print(f"Zeros Tensor: \n{zeros_tensor} \n")
print(f"Ones like x_data: \n{x_ones} \n")
print(f"Random like x_data: \n{x_rand} \n")

Data Tensor: 
tensor([[1, 2],
        [3, 4]]) 

From numpy array: 
tensor([[1, 2],
        [3, 4]]) 

Random Tensor: 
tensor([[0.4932, 0.0668, 0.8037],
        [0.7524, 0.0102, 0.8947]]) 

Ones Tensor: 
tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
tensor([[0., 0., 0.],
        [0., 0., 0.]]) 

Ones like x_data: 
tensor([[1, 1],
        [1, 1]]) 

Random like x_data: 
tensor([[0.7386, 0.6294],
        [0.3543, 0.7551]]) 



### Attributes of a tensor

In [19]:
my_tensor = torch.rand(2,2)

print(f"Shape of tensor: {my_tensor.shape}")
print(f"Datatype of tensor: {my_tensor.dtype}")
print(f"Device tensor is stored on: {my_tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


### Operation on tensors
Among the operations we can do, some are:
* moving the tensor to a different device
* indexing
* concatenation
* arithmetics

Often in machine learning we need to perform **matrix multiplication**, we will see three possible ways to do it

In [20]:
# If a GPU is available, move the tensor to GPU
if torch.cuda.is_available():
    my_tensor = my_tensor.to("cuda")
print(f"Device tensor is stored on: {my_tensor.device}")

Device tensor is stored on: cpu


In [21]:
# Indexing and slicing works as it does in numpy
print(my_tensor)
print(f"\nFirst row: {my_tensor[0]}")
print(f"First column: {my_tensor[:, 0]}")
print(f"Last column: {my_tensor[..., -1]}")

my_tensor[:,1] = 0
print(f"\nTensor after changing the second column: \n {my_tensor}")

tensor([[0.7921, 0.4517],
        [0.7299, 0.5789]])

First row: tensor([0.7921, 0.4517])
First column: tensor([0.7921, 0.7299])
Last column: tensor([0.4517, 0.5789])

Tensor after changing the second column: 
 tensor([[0.7921, 0.0000],
        [0.7299, 0.0000]])


In [24]:
# Joining tensors
t1 = torch.cat([my_tensor, my_tensor], dim=0) # Along existing dimension
print(f"Concatenation along existing dimension \n{t1} \n")

t2 = torch.stack([my_tensor, my_tensor], dim=0) # Creates a new dimension
print(f"Joining tensors with a new dimension \n{t2}")

Concatenation along existing dimension 
tensor([[0.7921, 0.0000],
        [0.7299, 0.0000],
        [0.7921, 0.0000],
        [0.7299, 0.0000]]) 

Joining tensors with a new dimension 
tensor([[[0.7921, 0.0000],
         [0.7299, 0.0000]],

        [[0.7921, 0.0000],
         [0.7299, 0.0000]]])


In [27]:
# Matrix multiplication
y1 = my_tensor @ my_tensor.T # tensor.T returns the transpose of the tensor
y2 = my_tensor.matmul(my_tensor.T)
# We can first create a tensor to store the output of our multiplication and then perform it
y3 = torch.rand_like(y1)
torch.matmul(my_tensor, my_tensor.T, out=y3)
# Let's verify that they all have the same values
print(f"y1 = {y1} \ny2 = {y2} \ny3 = {y3}")

y1 = tensor([[0.6274, 0.5781],
        [0.5781, 0.5327]]) 
y2 = tensor([[0.6274, 0.5781],
        [0.5781, 0.5327]]) 
y3 = tensor([[0.6274, 0.5781],
        [0.5781, 0.5327]])


In [28]:
# Element-wise product, again we can do it in three ways 
z1 = my_tensor * my_tensor
z2 = my_tensor.mul(my_tensor)
z3 = torch.rand_like(my_tensor)
torch.mul(my_tensor, my_tensor, out=z3)
print(f"z1 = {z1} \nz2 = {z2} \nz3 = {z3}")

z1 = tensor([[0.6274, 0.0000],
        [0.5327, 0.0000]]) 
z2 = tensor([[0.6274, 0.0000],
        [0.5327, 0.0000]]) 
z3 = tensor([[0.6274, 0.0000],
        [0.5327, 0.0000]])


### Bridge with numpy
Pytorch tensors and numpy arrays can share the same underlying memory, eliminating the need to copy data

In [29]:
# Tensor to NumPy array
t = torch.ones(5)
print(f"Tensor t: {t}")
n = t.numpy()
print(f"Numpy array n: {n}")

Tensor t: tensor([1., 1., 1., 1., 1.])
Numpy array n: [1. 1. 1. 1. 1.]


In [30]:
# A change in the tensor reflects in the NumPy array
t.add_(1)   # in-place addition
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


In [34]:
# NumPy array to Tensor
n = np.ones(2)
t = torch.from_numpy(n)
print(f"n: {n}")
print(f"t: {t}")

n: [1. 1.]
t: tensor([1., 1.], dtype=torch.float64)


In [35]:
# Changes in the NumPy array reflects in the tensor
np.add(n, 2, out=n)
print(f"n: {n}")
print(f"t: {t}")

n: [3. 3.]
t: tensor([3., 3.], dtype=torch.float64)
